---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: redis
    run_list:
      - recipe[twemproxy::default]
    attributes:
      twemproxy:
        config:
          alpha:
            listen: 127.0.0.1:22121
            hash: fnv1a_64
            distribution: ketama
            auto_eject_hosts: true
            redis: true
            server_retry_timeout: 2000
            server_failure_limit: 1
            servers:
            - 127.0.0.1:6379:1
  - name: memcache
    run_list:
      - recipe[memcached::default]
      - recipe[twemproxy::default]
    attributes:
      twemproxy:
        config:
          alpha:
            listen: 0.0.0.0:22121
            hash: fnv1a_64
            distribution: ketama
            preconnect: true
            auto_eject_hosts: false
            server_retry_timeout: 2000
            server_failure_limit: 3
            servers:
            - 127.0.0.1:11211:1
